FROM node:lts-alpine AS builder
WORKDIR /app
COPY .. .
RUN npm install
RUN npx nx build admin

FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/dist/apps/admin/.next ./.next
COPY --from=builder /app/apps/admin/public ./public
COPY ../package*.json ./
RUN npm ci --omit=dev
CMD ["npm", "start"]
