version: '3.8'

services:
  server:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.server
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env.server
    environment:
      NODE_ENV: production

  admin:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.admin
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env.admin
    environment:
      NODE_ENV: production
