FROM node:lts-alpine AS builder
WORKDIR /app
COPY .. .
RUN npm install
RUN npx nx build server

FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/dist/apps/server ./server
COPY ../package*.json ./
RUN npm ci --omit=dev
CMD ["node", "server/main.js"]
